## ----------------------------------------------------------------------------
## Script     : makefile.sources
## ----------------------------------------------------------------------------
## Author     : Johann Faerber
## Company    : University of Applied Sciences Augsburg
## ----------------------------------------------------------------------------
## Description: provide all the VHDL source files in the variable SYN_SOURCE_FILES
##              Attention !!!
##              -------------
##              Do not forget a new line after the final source file !
## ----------------------------------------------------------------------------

SYN_SOURCE_FILES = \
../../src/cnt4upmod10_qfsm.vhd \


# do not delete this line
# -----------------------------------------------------------------------------