## ----------------------------------------------------------------------------
## Script     : makefile.sources
## ----------------------------------------------------------------------------
## Author     : Johann Faerber
## Company    : University of Applied Sciences Augsburg
## ----------------------------------------------------------------------------
## Description: provide all the VHDL source files in the variable SYN_SOURCE_FILES
##              Attention !!!
##              -------------
##              Do not forget a new line after the final source file !
## ----------------------------------------------------------------------------

SYN_SOURCE_FILES = \
../../src/dregen_rtl.vhd \
../../src/add1_truthtable.vhd \
../../src/add4_structure.vhd \
../../src/cntupdn_structure.vhd \
../../src/resolver_qfsm.vhd \
../../src/incrementer_structure.vhd \

# do not delete this line
# -----------------------------------------------------------------------------
